"""
config/__init__.py — Re-exports all config symbols so existing imports keep working.

Import from sub-modules directly for new code:
    from ai.config.llm import CHAT_MODEL_PATH
    from ai.config.db  import NEO4J_URI
    from ai.config.app import STRIP_THINKING
"""
from .llm import (
    EMBED_MODEL_PATH, CHAT_MODEL_PATH, GRAPH_MODEL_PATH,
    EMBED_N_CTX, EMBED_N_GPU_LAYERS, EMBED_DIMENSIONS, EMBED_QUERY_PREFIX,
    USE_LOCAL_CHAT_MODEL,
    CHAT_N_CTX, CHAT_N_GPU_LAYERS, CHAT_MAX_TOKENS, CHAT_TEMPERATURE,
    DEEPSEEK_API_KEY, DEEPSEEK_BASE_URL, DEEPSEEK_MODEL_ID,
    DEEPSEEK_GRAPH_API_KEY, DEEPSEEK_GRAPH_BASE_URL, DEEPSEEK_GRAPH_MODEL_ID,
    OPENROUTER_API_KEY, OPENROUTER_BASE_URL, OPENROUTER_MODEL_ID,
    DEFAULT_CLOUD_MODEL,
)
from .db import (
    QDRANT_PATH, QDRANT_COLLECTION,
    NEO4J_URI, NEO4J_USER, NEO4J_PASSWORD,
    GRAPH_PATH,
)
from .app import (
    STRIP_THINKING,
    CONVERSE_MAX_CANDIDATES, CONVERSE_TOP_K_PER_DRUG,
    CONVERSE_STOP_THRESHOLD, CONVERSE_MAX_TURNS, CONVERSE_SCORE_GAP,
    CHUNKS_DIR,
)

__all__ = [
    # llm
    "EMBED_MODEL_PATH", "CHAT_MODEL_PATH", "GRAPH_MODEL_PATH",
    "EMBED_N_CTX", "EMBED_N_GPU_LAYERS", "EMBED_DIMENSIONS", "EMBED_QUERY_PREFIX",
    "USE_LOCAL_CHAT_MODEL",
    "CHAT_N_CTX", "CHAT_N_GPU_LAYERS", "CHAT_MAX_TOKENS", "CHAT_TEMPERATURE",
    "DEEPSEEK_API_KEY", "DEEPSEEK_BASE_URL", "DEEPSEEK_MODEL_ID",
    "DEEPSEEK_GRAPH_API_KEY", "DEEPSEEK_GRAPH_BASE_URL", "DEEPSEEK_GRAPH_MODEL_ID",
    "OPENROUTER_API_KEY", "OPENROUTER_BASE_URL", "OPENROUTER_MODEL_ID",
    "DEFAULT_CLOUD_MODEL",
    # db
    "QDRANT_PATH", "QDRANT_COLLECTION",
    "NEO4J_URI", "NEO4J_USER", "NEO4J_PASSWORD",
    "GRAPH_PATH",
    # app
    "STRIP_THINKING",
    "CONVERSE_MAX_CANDIDATES", "CONVERSE_TOP_K_PER_DRUG",
    "CONVERSE_STOP_THRESHOLD", "CONVERSE_MAX_TURNS", "CONVERSE_SCORE_GAP",
    "CHUNKS_DIR",
]
